spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/muru?autoReconnect=true&useSSL=false&useUnicode=yes
    username: root
    password: purpose
spring.jpa.properties.hibernate.id.new_generator_mappings: false
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

